import pytest
import os
import contextlib

# pq_graph options
# opt_level = 0 only tests correctness of the pq-generated equations
# opt_level > 0 tests correctness of code optimization with pq_graph. if you're patient, try opt_level = 6
pq_graph_options = {
    'batched': False,
    #'batched': True,
    #'batch_number': 100,
    'print_level': 0,
    'opt_level': 0,
    'nthreads': -1,
    'no_scalars': False,
}

# Initialize log file
LOG_FILE = "numerical_tests.log"
@pytest.fixture(scope="session", autouse=True)
def initialize_log_file():
    with open(LOG_FILE, "w") as f:
        f.write("============================================================\n")
        f.write("    AUTOGENERATED CODE GENERATION AND EXECUTION TEST LOG    \n")
        f.write("============================================================\n\n")
    yield  

import numpy as np
import psi4    

from pdaggerq.numerical_utils.cc import cc
from pdaggerq.numerical_utils.eom_cc import eom_ccsd

def setup_psi4_test():

    # set up job for psi4
    mol = psi4.geometry("""
    0 1
    O            0.000000000000     0.000000000000    -0.068516219320 
    H            0.000000000000    -0.790689573744     0.543701060715 
    H            0.000000000000     0.790689573744     0.543701060715 
    no_reorient
    nocom
    symmetry c1
    """)

    # set options
    psi4.set_options({'basis': 'sto-3g',
                      'scf_type': 'pk',
                      'reference': 'uhf',
                      'r_convergence': 1e-12,
                      'e_convergence': 1e-12,
                      'd_convergence': 1e-12})

    # compute the Hartree-Fock energy and wave function
    scf_e, wfn = psi4.energy('SCF', return_wfn=True)

    return mol, wfn

@pytest.mark.ccsd_disk
def test_ccsd_codegen_disk():

    import os
    import subprocess
    import sys
    import importlib
    
    # Setup paths
    script_path = os.path.dirname(os.path.realpath(__file__))
    gen_dir = os.path.join(script_path, "generated_equations")
    os.makedirs(gen_dir, exist_ok=True)
    
    # Add the generation directory to sys.path so Python can import from it
    if gen_dir not in sys.path:
        sys.path.insert(0, gen_dir)

    with open(LOG_FILE, "a") as f:
        f.write(">>> Running CCSD (functions on disk) ...\n")    

        with contextlib.redirect_stdout(f):

            # Import pq codegen functions 
            from pdaggerq.numerical_utils.autogen import cc_residual

            T = ['t1', 't2']
            cc_residual('cc_energy', T, [['1']], 'cc_energy', write_function = True, pq_graph_options = pq_graph_options)
            cc_residual('r1', T, [['e1(i,a)']], 't1_residual', write_function = True, pq_graph_options = pq_graph_options)
            cc_residual('r2', T, [['e2(i,j,b,a)']], 't2_residual', write_function = True, pq_graph_options = pq_graph_options)

            # define the autogenerated module names we want to import
            module_names = ["cc_energy", "t1_residual", "t2_residual"]
            local_namespace = {}

            # import each pq-generated file
            for name in module_names:
                if name in sys.modules:
                    importlib.reload(sys.modules[name])
                local_namespace[name] = importlib.import_module(name)

            # amplitude dictionaries to pass into the solver
            t1 = {
                'spaces' : 'vo',
                'spins' : ['aa', 'bb'],
                'residual' : local_namespace["t1_residual"].t1_residual
            }
            t2 = {
                'spaces' : 'vvoo',
                'spins' : ['aaaa', 'abab', 'bbbb'],
                'residual' : local_namespace["t2_residual"].t2_residual
            }

            # Pass pq-generated functions into the cc solver
            mol, wfn = setup_psi4_test()
            mycc = cc(
                wfn,
                mol,
                nfzc=1,
                cc_energy_func=local_namespace["cc_energy"].cc_energy,
                T_list = [t1, t2]
            )

            en = mycc.t_solver()

            assert np.isclose(en, -75.019641774768, rtol=1e-10, atol=1e-10)

        f.write(">>> TEST PASSED: CCSD (functions on disk)\n")    

@pytest.mark.qed_ccsd
def test_qed_ccsd_codegen():

    with open(LOG_FILE, "a") as f:
        f.write(">>> Running QED-CCSD-21 ...\n")

        with contextlib.redirect_stdout(f):

            # Import pq codegen functions 
            from pdaggerq.numerical_utils.autogen import cc_residual

            # Create an empty dictionary to hold the pq-generated equations
            local_namespace = {}

            # Generate equations
            T = ['t1', 't2', 't0,1', 't1,1', 't2,1']

            cc_energy_func = cc_residual('cc_energy', 
                T, 
                [['1']], 
                'cc_energy', 
                is_qed = True, 
                pq_graph_options = pq_graph_options
            )

            t1_residual_func = cc_residual('r1', 
                T, 
                [['e1(i,a)']], 
                't1_residual', 
                is_qed = True, 
                pq_graph_options = pq_graph_options
            )

            t2_residual_func = cc_residual('r2', 
                T, 
                [['e2(i,j,b,a)']], 
                't2_residual', 
                is_qed = True, 
                pq_graph_options = pq_graph_options
            )

            t0_1p_residual_func = cc_residual('r0_1p', 
                T, 
                [['B-']], 
                't0_1p_residual', 
                is_qed = True, 
                pq_graph_options = pq_graph_options
            )

            t1_1p_residual_func = cc_residual('r1_1p', 
                T, 
                [['B-','e1(i,a)']], 
                't1_1p_residual', 
                is_qed = True, 
                pq_graph_options = pq_graph_options
            )

            t2_1p_residual_func = cc_residual('r2_1p', 
                T, 
                [['B-','e2(i,j,b,a)']], 
                't2_1p_residual', 
                is_qed = True, 
                pq_graph_options = pq_graph_options
            )

            # Execute the code strings in memory
            exec(cc_energy_func, globals(), local_namespace)
            exec(t1_residual_func, globals(), local_namespace)
            exec(t2_residual_func, globals(), local_namespace)
            exec(t0_1p_residual_func, globals(), local_namespace)
            exec(t1_1p_residual_func, globals(), local_namespace)
            exec(t2_1p_residual_func, globals(), local_namespace)

            # amplitude dictionaries to pass into the solver
            t1 = {
                'spaces' : 'vo', 
                'spins' : ['aa', 'bb'],
                'residual' : local_namespace["t1_residual"]
            }
            t2 = {
                'spaces' : 'vvoo',
                'spins' : ['aaaa', 'abab', 'bbbb'],
                'residual' : local_namespace["t2_residual"]
            }
            t0_1p = {
                'nph' : 1,
                'residual' : local_namespace["t0_1p_residual"]
            }
            t1_1p = {
                'nph' : 1,
                'spaces' : 'vo',
                'spins' : ['aa', 'bb'],
                'residual' : local_namespace["t1_1p_residual"]
            }
            t2_1p = {
                'nph' : 1,
                'spaces' : 'vvoo',
                'spins' : ['aaaa', 'abab', 'bbbb'],
                'residual' : local_namespace["t2_1p_residual"]
            }

            # Pass pq-generated functions into the cc solver
            mol, wfn = setup_psi4_test()
            mycc = cc(
                wfn,
                mol,
                nfzc=0,
                cc_energy_func=local_namespace["cc_energy"],
                T_list = [t1, t2, t0_1p, t1_1p, t2_1p],
                is_qed = True, 
                cavity_lambda=[0.0, 0.0, 0.05],
                cavity_frequency=0.07349864501573 # 2eV
            )

            en = mycc.t_solver()

            assert np.isclose(en, -75.015650410563, rtol=1e-10, atol=1e-10)

        f.write(">>> TEST PASSED: QED-CCSD-21\n")

@pytest.mark.ccsd
def test_ccsd_codegen():

    with open(LOG_FILE, "a") as f:
        f.write(">>> Running CCSD ...\n")

        with contextlib.redirect_stdout(f):

            # Import pq codegen functions 
            from pdaggerq.numerical_utils.autogen import cc_residual

            # Create an empty dictionary to hold the pq-generated equations
            local_namespace = {}
            
            # Generate equations
            T = ['t1', 't2']

            cc_energy_func = cc_residual('cc_energy',
                T,
                [['1']],
                'cc_energy',
                pq_graph_options = pq_graph_options
            )

            t1_residual_func = cc_residual('r1',
                T,
                [['e1(i,a)']],
                't1_residual',
                pq_graph_options = pq_graph_options
            )

            t2_residual_func = cc_residual('r2',
                T,
                [['e2(i,j,b,a)']],
                't2_residual',
                pq_graph_options = pq_graph_options
            )

            # Execute the code strings in memory
            exec(cc_energy_func, globals(), local_namespace)
            exec(t1_residual_func, globals(), local_namespace)
            exec(t2_residual_func, globals(), local_namespace)

            # amplitude dictionaries to pass into the solver
            t1 = {
                'spaces' : 'vo',
                'spins' : ['aa', 'bb'],
                'residual' : local_namespace["t1_residual"]
            }
            t2 = {
                'spaces' : 'vvoo',
                'spins' : ['aaaa', 'abab', 'bbbb'],
                'residual' : local_namespace["t2_residual"]
            }
            
            # Pass pq-generated functions into the cc solver
            mol, wfn = setup_psi4_test()
            mycc = cc(
                wfn, 
                mol, 
                nfzc=1, 
                cc_energy_func=local_namespace["cc_energy"],
                T_list = [t1, t2],
            )

            en = mycc.t_solver()

            assert np.isclose(en, -75.019641774768, rtol=1e-10, atol=1e-10)

        f.write(">>> TEST PASSED: CCSD\n")    

@pytest.mark.ucc3
def test_uccsd_3_codegen():

    with open(LOG_FILE, "a") as f:
        f.write(">>> Running UCCSD(3) ...\n")

        with contextlib.redirect_stdout(f):

            # Import pq codegen functions 
            from pdaggerq.numerical_utils.autogen import uccsd_energy
            from pdaggerq.numerical_utils.autogen import uccsd_singles_residual
            from pdaggerq.numerical_utils.autogen import uccsd_doubles_residual

            # Create an empty dictionary to hold the pq-generated equations
            local_namespace = {}
            
            # Generate equations
            cc_energy_func = uccsd_energy(3,
                'cc_energy',
                'cc_energy',
                pq_graph_options = pq_graph_options
            )

            t1_residual_func = uccsd_singles_residual(2,
                'r1',
                [['e1(i,a)']],
                't1_residual',
                pq_graph_options = pq_graph_options
            )
            
            t2_residual_func = uccsd_doubles_residual(2,
                'r2',
                [['e2(i,j,b,a)']],
                't2_residual',
                pq_graph_options = pq_graph_options
            )

            # Execute the code strings in memory
            exec(cc_energy_func, globals(), local_namespace)
            exec(t1_residual_func, globals(), local_namespace)
            exec(t2_residual_func, globals(), local_namespace)

            # amplitude dictionaries to pass into the solver
            t1 = {
                'spaces' : 'vo',
                'spins' : ['aa', 'bb'],
                'residual' : local_namespace["t1_residual"]
            }
            t2 = {
                'spaces' : 'vvoo',
                'spins' : ['aaaa', 'abab', 'bbbb'],
                'residual' : local_namespace["t2_residual"]
            }

            # Pass pq-generated functions into the cc solver
            mol, wfn = setup_psi4_test()
            mycc = cc(
                wfn, 
                mol, 
                nfzc=1, 
                cc_energy_func=local_namespace["cc_energy"], 
                T_list = [t1, t2]
            )

            en = mycc.t_solver()

            assert np.isclose(en, -75.020242934640, rtol=1e-10, atol=1e-10)

        f.write(">>> TEST PASSED: UCCSD(3)\n")    

@pytest.mark.ucc4
def test_uccsd_4_codegen():

    with open(LOG_FILE, "a") as f:
        f.write(">>> Running UCCSD(4) ...\n")

        with contextlib.redirect_stdout(f):

            # Import pq codegen functions 
            from pdaggerq.numerical_utils.autogen import uccsd_energy
            from pdaggerq.numerical_utils.autogen import uccsd_singles_residual
            from pdaggerq.numerical_utils.autogen import uccsd_doubles_residual

            # Create an empty dictionary to hold the pq-generated equations
            local_namespace = {}

            # Generate equations
            cc_energy_func = uccsd_energy(4,
                'cc_energy',
                'cc_energy',
                pq_graph_options = pq_graph_options
            )   
                
            t1_residual_func = uccsd_singles_residual(3,
                'r1',
                [['e1(i,a)']],
                't1_residual',
                pq_graph_options = pq_graph_options
            )

            t2_residual_func = uccsd_doubles_residual(3,
                'r2',
                [['e2(i,j,b,a)']],
                't2_residual',
                pq_graph_options = pq_graph_options
            )

            # Execute the code strings in memory
            exec(cc_energy_func, globals(), local_namespace)
            exec(t1_residual_func, globals(), local_namespace)
            exec(t2_residual_func, globals(), local_namespace)

            # amplitude dictionaries to pass into the solver
            t1 = {
                'spaces' : 'vo',
                'spins' : ['aa', 'bb'],
                'residual' : local_namespace["t1_residual"]
            }
            t2 = {
                'spaces' : 'vvoo',
                'spins' : ['aaaa', 'abab', 'bbbb'],
                'residual' : local_namespace["t2_residual"]
            }

            # Pass pq-generated functions into the cc solver
            mol, wfn = setup_psi4_test()
            mycc = cc(
                wfn,
                mol,
                nfzc=1,
                cc_energy_func=local_namespace["cc_energy"], 
                T_list = [t1, t2]
            )

            en = mycc.t_solver()

            assert np.isclose(en, -75.019695059108, rtol=1e-10, atol=1e-10)

        f.write(">>> TEST PASSED: UCCSD(4)\n")    

@pytest.mark.quccsd
def test_quccsd_codegen():

    with open(LOG_FILE, "a") as f:
        f.write(">>> Running QUCCSD ...\n")

        with contextlib.redirect_stdout(f):

            # Import pq codegen functions 
            from pdaggerq.numerical_utils.autogen import bernoulli_ucc_residual

            # Create an empty dictionary to hold the pq-generated equations
            local_namespace = {}

            # Generate equations
            T = ['t1', 't2'] 
            
            cc_energy_func = bernoulli_ucc_residual(3,
                'cc_energy',
                T, 
                [['1']], 
                'cc_energy', 
                pq_graph_options = pq_graph_options
            )   
            
            t1_residual_func = bernoulli_ucc_residual(2,
                'r1',
                T,
                [['e1(i,a)']],
                't1_residual', 
                pq_graph_options = pq_graph_options
            )   
                
            t2_residual_func = bernoulli_ucc_residual(2,
                'r2',
                T,
                [['e2(i,j,b,a)']],
                't2_residual',
                pq_graph_options = pq_graph_options
            )   
                
            # Execute the code strings in memory
            exec(cc_energy_func, globals(), local_namespace)
            exec(t1_residual_func, globals(), local_namespace)
            exec(t2_residual_func, globals(), local_namespace)

            # amplitude dictionaries to pass into the solver
            t1 = {
                'spaces' : 'vo',
                'spins' : ['aa', 'bb'],
                'residual' : local_namespace["t1_residual"]
            }
            t2 = {
                'spaces' : 'vvoo',
                'spins' : ['aaaa', 'abab', 'bbbb'],
                'residual' : local_namespace["t2_residual"]
            }

            # Pass pq-generated functions into the cc solver
            mol, wfn = setup_psi4_test()
            mycc = cc(
                wfn,
                mol,
                nfzc=1,
                cc_energy_func=local_namespace["cc_energy"], 
                T_list = [t1, t2]
            )

            en = mycc.t_solver()

            assert np.isclose(en, -75.019629416631, rtol=1e-10, atol=1e-10)

        f.write(">>> TEST PASSED: QUCCSD\n")    

@pytest.mark.lambda_ccsd
def test_lambda_ccsd_codegen():

    with open(LOG_FILE, "a") as f:
        f.write(">>> Running lambda-CCSD ...\n")

        with contextlib.redirect_stdout(f):
        
            # Import pq codegen functions 
            from pdaggerq.numerical_utils.autogen import cc_residual
            from pdaggerq.numerical_utils.autogen import lambda_cc_residual
            from pdaggerq.numerical_utils.autogen import lambda_cc_pseudoenergy
                
            # Create an empty dictionary to hold the pq-generated equations
            local_namespace = {}

            # Generate equations
            T = ['t1', 't2'] 

            cc_energy_func = cc_residual('cc_energy',
                T, 
                [['1']],
                'cc_energy',
                pq_graph_options = pq_graph_options
            )   
            
            t1_residual_func = cc_residual('r1',
                T,
                [['e1(i,a)']],
                't1_residual', 
                pq_graph_options = pq_graph_options
            )   
                
            t2_residual_func = cc_residual('r2',
                T,
                [['e2(i,j,b,a)']],
                't2_residual',
                pq_graph_options = pq_graph_options
            )   
                
            # Execute the code strings in memory
            exec(cc_energy_func, globals(), local_namespace)
            exec(t1_residual_func, globals(), local_namespace)
            exec(t2_residual_func, globals(), local_namespace)

            # amplitude dictionaries to pass into the solver
            t1 = {
                'spaces' : 'vo',
                'spins' : ['aa', 'bb'],
                'residual' : local_namespace["t1_residual"]
            }
            t2 = {
                'spaces' : 'vvoo',
                'spins' : ['aaaa', 'abab', 'bbbb'],
                'residual' : local_namespace["t2_residual"]
            }
   
            # Generate lambda equations
            L = [['l1'], ['l2']]

            cc_pseudoenergy_func = lambda_cc_pseudoenergy('cc_pseudoenergy',
                L,
                [['1']],
                'cc_pseudoenergy',
                pq_graph_options = pq_graph_options
            )

            l1_residual_func = lambda_cc_residual('r1',
                T,
                L,
                'e1(a,i)',
                'l1_residual',
                pq_graph_options = pq_graph_options
            )

            l2_residual_func = lambda_cc_residual('r2',
                T,
                L,
                'e2(a,b,j,i)',
                'l2_residual',
                pq_graph_options = pq_graph_options
            )

            # Execute the code strings in memory
            exec(cc_pseudoenergy_func, globals(), local_namespace)
            exec(l1_residual_func, globals(), local_namespace)
            exec(l2_residual_func, globals(), local_namespace)

            # lambda amplitude dictionaries to pass into the solver
            l1 = {
                'spaces' : 'vo',
                'spins' : ['aa', 'bb'],
                'residual' : local_namespace["l1_residual"]
            }
            l2 = {
                'spaces' : 'vvoo',
                'spins' : ['aaaa', 'abab', 'bbbb'],
                'residual' : local_namespace["l2_residual"]
            }

            # Pass pq-generated functions into the cc solver
            mol, wfn = setup_psi4_test()

            mycc = cc(
                wfn, 
                mol,
                nfzc=1,
                cc_energy_func=local_namespace["cc_energy"],
                cc_pseudoenergy_func=local_namespace["cc_pseudoenergy"],
                T_list = [t1, t2],
                L_list = [l1, l2],
            )
            
            en = mycc.t_solver()

            assert np.isclose(en, -75.019641774768, rtol=1e-10, atol=1e-10)

            pseudoen = mycc.lambda_solver()

            assert np.isclose(pseudoen, -0.054046897553, rtol=1e-10, atol=1e-10)

        f.write(">>> TEST PASSED: lambda-CCSD\n")    

@pytest.mark.ccsdt
def test_ccsdt_codegen():

    with open(LOG_FILE, "a") as f:
        f.write(">>> Running CCSDT ...\n")

        with contextlib.redirect_stdout(f):

            # Import pq codegen functions 
            from pdaggerq.numerical_utils.autogen import cc_residual

            # Create an empty dictionary to hold the pq-generated equations
            local_namespace = {}
           
            # Generate equations
            T = ['t1', 't2', 't3'] 

            cc_energy_func = cc_residual('cc_energy',
                T, 
                [['1']],
                'cc_energy',
                pq_graph_options = pq_graph_options
            )   
            
            t1_residual_func = cc_residual('r1',
                T,
                [['e1(i,a)']],
                't1_residual', 
                pq_graph_options = pq_graph_options
            )   
                
            t2_residual_func = cc_residual('r2',
                T,
                [['e2(i,j,b,a)']],
                't2_residual',
                pq_graph_options = pq_graph_options
            )   
                
            t3_residual_func = cc_residual('r3',
                T,
                [['e3(i,j,k,c,b,a)']],
                't3_residual',
                pq_graph_options = pq_graph_options
            )   

            # Execute the code strings in memory
            exec(cc_energy_func, globals(), local_namespace)
            exec(t1_residual_func, globals(), local_namespace)
            exec(t2_residual_func, globals(), local_namespace) 
            exec(t3_residual_func, globals(), local_namespace) 

            # amplitude dictionaries to pass into the solver
            t1 = {
                'spaces' : 'vo',
                'spins' : ['aa', 'bb'],
                'residual' : local_namespace["t1_residual"]
            }
            t2 = {
                'spaces' : 'vvoo',
                'spins' : ['aaaa', 'abab', 'bbbb'],
                'residual' : local_namespace["t2_residual"]
            }
            t3 = {
                'spaces' : 'vvvooo',
                'spins' : ['aaaaaa', 'aabaab', 'abbabb', 'bbbbbb'],
                'residual' : local_namespace["t3_residual"]
            }
            
            # Pass pq-generated functions into the cc solver
            mol, wfn = setup_psi4_test()
            mycc = cc(
                wfn,
                mol, 
                nfzc=1,  
                cc_energy_func=local_namespace["cc_energy"],
                T_list = [t1, t2, t3],
            )

            en = mycc.t_solver()

            assert np.isclose(en, -75.019746392571, rtol=1e-10, atol=1e-10)

        f.write(">>> TEST PASSED: CCSDT\n")    

@pytest.mark.cc3
def test_cc3_codegen():

    with open(LOG_FILE, "a") as f:
        f.write(">>> Running CC3 ...\n")

        with contextlib.redirect_stdout(f):

            # Import pq codegen functions 
            from pdaggerq.numerical_utils.autogen import cc_residual
            from pdaggerq.numerical_utils.autogen import cc3_triples_residual

            # Create an empty dictionary to hold the pq-generated equations
            local_namespace = {}

            # Generate equations
            T = ['t1', 't2', 't3']

            cc_energy_func = cc_residual('cc_energy',
                T,
                [['1']],
                'cc_energy',
                pq_graph_options = pq_graph_options
            )  

            t1_residual_func = cc_residual('r1',
                T,
                [['e1(i,a)']],
                't1_residual',
                pq_graph_options = pq_graph_options
            )  

            t2_residual_func = cc_residual('r2',
                T,
                [['e2(i,j,b,a)']],
                't2_residual',
                pq_graph_options = pq_graph_options
            )

            t3_residual_func = cc3_triples_residual('r3',
                [['e3(i,j,k,c,b,a)']],
                't3_residual',
                pq_graph_options = pq_graph_options
            )  

            # Execute the code strings in memory
            exec(cc_energy_func, globals(), local_namespace)
            exec(t1_residual_func, globals(), local_namespace)
            exec(t2_residual_func, globals(), local_namespace)
            exec(t3_residual_func, globals(), local_namespace)

            # amplitude dictionaries to pass into the solver
            t1 = {
                'spaces' : 'vo',
                'spins' : ['aa', 'bb'],
                'residual' : local_namespace["t1_residual"]
            }
            t2 = {
                'spaces' : 'vvoo',
                'spins' : ['aaaa', 'abab', 'bbbb'],
                'residual' : local_namespace["t2_residual"]
            }
            t3 = {
                'spaces' : 'vvvooo',
                'spins' : ['aaaaaa', 'aabaab', 'abbabb', 'bbbbbb'],
                'residual' : local_namespace["t3_residual"]
            }

            # Pass pq-generated functions into the cc solver
            mol, wfn = setup_psi4_test()
            mycc = cc(
                wfn,
                mol, 
                nfzc=1,  
                cc_energy_func=local_namespace["cc_energy"],
                T_list = [t1, t2, t3]
            )

            en = mycc.t_solver()

            assert np.isclose(en, -75.019717612241, rtol=1e-10, atol=1e-10)

        f.write(">>> TEST PASSED: CC3\n")    

@pytest.mark.eomcc
def test_eomccsd_codegen():

    with open(LOG_FILE, "a") as f:
        f.write(">>> Running EOMCCSD ...\n")

        with contextlib.redirect_stdout(f):

            # Import pq cc codegen function 
            from pdaggerq.numerical_utils.autogen import cc_residual

            # Create an empty dictionary to hold the pq-generated equations
            local_namespace = {}

            # Generate equations
            T = ['t1', 't2'] 

            cc_energy_func = cc_residual('cc_energy',
                T, 
                [['1']],
                'cc_energy',
                pq_graph_options = pq_graph_options
            )   
            
            t1_residual_func = cc_residual('r1',
                T,
                [['e1(i,a)']],
                't1_residual', 
                pq_graph_options = pq_graph_options
            )   
                
            t2_residual_func = cc_residual('r2',
                T,
                [['e2(i,j,b,a)']],
                't2_residual',
                pq_graph_options = pq_graph_options
            )   
                
            # Execute the code strings in memory
            exec(cc_energy_func, globals(), local_namespace)
            exec(t1_residual_func, globals(), local_namespace)
            exec(t2_residual_func, globals(), local_namespace)

            # amplitude dictionaries to pass into the solver
            t1 = {
                'spaces' : 'vo', 
                'spins' : ['aa', 'bb'],
                'residual' : local_namespace["t1_residual"]
            }
            t2 = {
                'spaces' : 'vvoo',
                'spins' : ['aaaa', 'abab', 'bbbb'],
                'residual' : local_namespace["t2_residual"]
            }

            # Import pq eomcc codegen function
            from pdaggerq.numerical_utils.autogen import eomcc_sigma

            # Generate right-hand sigma equations
            R = [['r0'], ['r1'], ['r2']]

            right_sigma0_func = eomcc_sigma('sigma0',
                T,
                [['1']],
                R,
                'right_sigma0', 
                pq_graph_options = pq_graph_options
            )

            right_sigma1_func = eomcc_sigma('sigma1',
                T,
                [['e1(i,a)']],
                R,
                'right_sigma1', 
                pq_graph_options = pq_graph_options
            )

            right_sigma2_func = eomcc_sigma('sigma2',
                T,
                [['e2(i,j,b,a)']],
                R,
                'right_sigma2', 
                pq_graph_options = pq_graph_options
            )

            # Execute the code strings in memory
            exec(right_sigma0_func, globals(), local_namespace)
            exec(right_sigma1_func, globals(), local_namespace)
            exec(right_sigma2_func, globals(), local_namespace)

            # Generate left-hand sigma equations
            L = [['l0'], ['l1'], ['l2']]

            left_sigma0_func = eomcc_sigma('sigma0',
                T,
                L,
                [['1']],
                'left_sigma0',
                pq_graph_options = pq_graph_options
            )

            left_sigma1_func = eomcc_sigma('sigma1',
                T,
                L,
                [['e1(a,i)']],
                'left_sigma1',
                pq_graph_options = pq_graph_options
            )

            left_sigma2_func = eomcc_sigma('sigma2',
                T,
                L,
                [['e2(a,b,j,i)']],
                'left_sigma2',
                pq_graph_options = pq_graph_options
            )

            # Execute the code strings in memory
            exec(left_sigma0_func, globals(), local_namespace)
            exec(left_sigma1_func, globals(), local_namespace)
            exec(left_sigma2_func, globals(), local_namespace)

            # Import pq eomcc density matrix codegen function
            from pdaggerq.numerical_utils.autogen import eomcc_density_matrix

            # Generate transition density matrix equations

            tdm_func = eomcc_density_matrix('tdm', 
                T, 
                L, 
                R, 
                'density_matrix', 
                pq_graph_options = pq_graph_options
            )
            
            # Execute the code string in memory
            exec(tdm_func, globals(), local_namespace)

            # Pass pq-generated functions into the cc solver
            mol, wfn = setup_psi4_test()
            mycc = cc(
                wfn, 
                mol, 
                nfzc=1, 
                cc_energy_func=local_namespace["cc_energy"],
                T_list = [t1, t2]
            )

            en = mycc.t_solver()

            assert np.isclose(en, -75.019641774768, rtol=1e-10, atol=1e-10)

            eomcc = eom_ccsd(mycc, 
                right_sigma0_func=local_namespace["right_sigma0"],
                right_sigma1_func=local_namespace["right_sigma1"],
                right_sigma2_func=local_namespace["right_sigma2"],
                left_sigma0_func=local_namespace["left_sigma0"],
                left_sigma1_func=local_namespace["left_sigma1"],
                left_sigma2_func=local_namespace["left_sigma2"],
                density_matrix_func=local_namespace["density_matrix"]
             )

            ref_energies = [0.000000000000,
                0.356359777102,
                0.412605450358,
                0.457799399030,
                0.457998414869,
            ]

            eomcc.right_solver()

            assert np.allclose(ref_energies, eomcc.eom_cc_energy, rtol=1e-10, atol=1e-10)

            eomcc.left_solver()

            assert np.allclose(ref_energies, eomcc.eom_cc_energy, rtol=1e-10, atol=1e-10)

            osc = eomcc.oscillator_strengths()

            ref_osc = [0.000000000000,
                0.002810870965,
                0.000000000000,
                0.000000000000,
                0.000000000000,
                0.054163450493,
                0.000683020239,
                0.000000000000,
                0.000000000000,
                0.000000000000,
            ]
            idx = 0
            for i in range (5):
                for j in range (i+1, 5):
                    assert np.isclose(osc[i, j], ref_osc[idx], rtol=1e-10, atol=1e-10)
                    idx += 1

        f.write(">>> TEST PASSED: EOMCCSD\n")    

def main():
    #test_ccsd_codegen_disk()
    #test_ccsd_codegen()
    #test_qed_ccsd_codegen()
    #test_ccsdt_codegen()
    #test_cc3_codegen()
    #test_eomccsd_codegen()
    test_lambda_ccsd_codegen()
    #test_uccsd_3_codegen()
    #test_uccsd_4_codegen()
    #test_quccsd_codegen()
    #raise Exception("run with pytest")

if __name__ == "__main__":
    main()

