# -*- coding: utf-8 -*-
"""
Multicomponent (nuclear-electronic, NEO) equations through pq_opt.

Each NEO residual is generated by pq_graph at opt_level 0 (a direct transcription of
pdaggerq's terms) and by pq_opt at opt_levels 0 and 1, and every version is run on
the same random tensors; all must agree. This checks pq_opt's handling of nuclear
indices (spaces O/V), amplitude names (t2_n, t2_ep, t3_ep21), and integral blocks
(f["OO"], g["vVoO"]) against an independent code generator.

pq_graph and pq_opt may write the same <p,q||r,s> as different, equivalent eri
blocks, so the electron and nuclear eri tensors are antisymmetric. Everything else
is arbitrary: both generators transcribe the same simplified pdaggerq terms.
"""

import re
import zlib
from itertools import permutations

import numpy as np
import pdaggerq
import pytest

pytestmark = pytest.mark.neo

D = 3  # occupied and virtual dimension, the same for electrons and nuclei

HAMILTONIAN = ["f", "fp", "v", "vp", "gep"]

# name -> (projection, T operators, lhs label order)
CASES = {
    "electron doubles": ("e2(i,j,a,b)", ["t2", "tp2", "tep11"], ["a", "b", "i", "j"]),
    "mixed e-p doubles": ("e2(i,ni,a,na)", ["t2", "tp2", "tep11"], ["a", "i", "na", "ni"]),
    "proton singles": ("e1(ni,na)", ["t1", "t2", "tp1", "tep11"], ["na", "ni"]),
    "mixed eep triples": ("e3(i,j,ni,a,b,na)", ["t1", "t2", "tp1", "tep11", "tep21"],
                          ["a", "b", "i", "j", "na", "ni"]),
}


def equation(projection, T):
    pq = pdaggerq.pq_helper("fermi")
    pq.set_left_operators([[projection]])
    for h in HAMILTONIAN:
        pq.add_st_operator(1.0, [h], T, True, 2)
    pq.simplify()
    return pq


def generate(generator, level, pq, order):
    options = {"opt_level": level, "print_level": 0}
    g = pdaggerq.pq_graph(options) if generator == "pq_graph" else pdaggerq.pq_opt(options)
    g.add(pq, "r", order)
    g.optimize()
    return "\n".join(g.to_strings("python"))


def random(name, shape):
    return np.random.default_rng(zlib.crc32(name.encode())).standard_normal(shape)


def antisymmetric(name):
    x = random(name, (2 * D,) * 4)
    x = x - x.transpose(1, 0, 2, 3)
    return x - x.transpose(0, 1, 3, 2)


# full tensors over [occupied, virtual] of one species; g couples electrons and nuclei
FULL = {"f_e": random("f_e", (2 * D, 2 * D)), "f_n": random("f_n", (2 * D, 2 * D)),
        "eri_e": antisymmetric("eri_e"), "eri_n": antisymmetric("eri_n"),
        "g": random("g", (2 * D,) * 4)}


def block(full, key):
    """the block of a full tensor named by its key's spaces, e.g. 'vVoO'"""
    return full[np.ix_(*[range(0, D) if c in "oO" else range(D, 2 * D) for c in key])]


def amplitude(name):
    """a random amplitude, antisymmetric among its same-species creation and annihilation
    labels (e.g. a,b of t3_ep21(a,b,na,i,j,ni)), as pq_opt assumes"""
    order = int(name[1])
    x = random(name, (D,) * (2 * order))
    # t*_ep<e><p> has <e> electron labels per half (t2_ep: 1). pdaggerq writes the creation
    # half electrons first and the annihilation half nuclei first: t3_ep21(b,a,na,ni,j,k)
    split = re.fullmatch(r"t\d_ep(\d)(\d)", name)
    n_electron = int(split.group(1)) if split else (1 if name.endswith("_ep") else order)
    n_nuclear = order - n_electron if (split or name.endswith("_ep")) else 0
    for start, first in ((0, n_electron), (order, n_nuclear if n_nuclear else n_electron)):
        for lo, hi in ((start, start + first), (start + first, start + order)):
            axes = list(range(lo, hi))
            if len(axes) > 1:
                total = np.zeros_like(x)
                for perm in permutations(range(len(axes))):
                    sign = (-1) ** sum(perm[i] > perm[j] for i in range(len(perm)) for j in range(i + 1, len(perm)))
                    order_ = list(range(x.ndim))
                    for axis, p in zip(axes, perm):
                        order_[axis] = axes[p]
                    total += sign * np.transpose(x, order_)
                x = total
    return x


def evaluate(code):
    keys = lambda name: set(re.findall(name + r'\["([a-zA-Z]+)"\]', code))
    species = lambda key: "n" if key.isupper() else "e"
    ns = {"np": np, "einsum": np.einsum, "tmps_": {}, "scalars_": {}, "perm_tmps": {}}
    ns["f"] = {k: block(FULL["f_" + species(k)], k) for k in keys("f")}
    ns["eri"] = {k: block(FULL["eri_" + species(k)], k) for k in keys("eri")}
    ns["g"] = {k: block(FULL["g"], k) for k in keys("g")}
    ns["Id"] = {k: np.eye(D) for k in keys("Id")}
    for name in set(re.findall(r"\b(t\d(?:_n|_ep\d*)?)\b", code)):
        ns[name] = amplitude(name)
    body = "\n".join(l.strip() for l in code.splitlines() if l.strip() and not l.strip().startswith("#"))
    exec(body, ns)
    return np.asarray(ns["r"])


@pytest.mark.parametrize("case", CASES)
def test_pq_opt_matches_pq_graph(case):
    projection, T, order = CASES[case]
    pq = equation(projection, T)
    reference = evaluate(generate("pq_graph", 0, pq, order))
    assert np.abs(reference).max() > 1e-3, f"{case}: residual is trivially zero"
    for level in (0, 1, 2):
        result = evaluate(generate("pq_opt", level, pq, order))
        np.testing.assert_allclose(result, reference, rtol=1e-10, atol=1e-10,
                                   err_msg=f"{case}: pq_opt at opt_level {level} differs from pq_graph")


SPIN_BLOCKED = r"""
import re, pdaggerq
from pdaggerq.spin import get_spin_labels
pq = pdaggerq.pq_helper("fermi"); pq.set_left_operators([["e2(i,ni,a,na)"]])
pq.add_st_operator(1.0, ["gep"], ["t2", "tep11"], True, 2); pq.simplify()
pq.block_by_spin(get_spin_labels([["e2(i,ni,a,na)"]], "high-spin")["aa_n"])
g = pdaggerq.pq_opt({"opt_level": 1}); g.add(pq, "R", ["a", "i", "na", "ni"])
print("\n".join(g.to_strings("python")))
"""


def test_spin_blocks_keep_species_distinct():
    # spin blocking must not merge the electron doubles t2 with the mixed amplitude t2_ep:
    # both keep their name, with the spin block as the key. (A subprocess, because spin
    # blocking sets a process-wide flag in pdaggerq.)
    import subprocess, sys
    result = subprocess.run([sys.executable, "-c", SPIN_BLOCKED], capture_output=True, text=True)
    assert result.returncode == 0, result.stderr[-2000:]
    code = result.stdout
    assert re.search(r'\bt2\["(aaaa|abab)"\]', code), "electron doubles t2 block missing"
    assert re.search(r'\bt2_ep\["(aaaa|abab)"\]', code), "mixed t2_ep block missing or merged with t2"


if __name__ == "__main__":
    print("Please use pytest to run the tests")
