import numpy as np
import psi4    
import os
import subprocess
import sys
import importlib

from pdaggerq.numerical_utils.cc import cc
from pdaggerq.numerical_utils.eom_cc import eom_ccsd

# Setup paths
script_path = os.path.dirname(os.path.realpath(__file__))
gen_dir = os.path.join(script_path, "generated_equations")
print(gen_dir)
os.makedirs(gen_dir, exist_ok=True)

# Add the generation directory to sys.path so Python can import from it
if gen_dir not in sys.path:
    sys.path.insert(0, gen_dir)

def setup_psi4_test():

    # set up job for psi4
    mol = psi4.geometry("""
    0 1
    O
    H 1 1.0
    H 1 1.0 2 104.5
    #H            0.000000000000     0.000000000000     0.000000000000 
    #F            0.000000000000     0.000000000000     3.023561812617  
    #units bohr
    symmetry c1
    """)

    # set options
    psi4.set_options({'basis': 'sto-3g',
                      'scf_type': 'pk',
                      'reference': 'uhf',
                      'e_convergence': 1e-12,
                      'd_convergence': 1e-12})

    # compute the Hartree-Fock energy and wave function
    scf_e, wfn = psi4.energy('SCF', return_wfn=True)

    return mol, wfn

def test_ccsdt_codegen():

    # pq codegen 
    codegen_script = os.path.join(script_path, "test_cases/ccsdt_codegen.py")
    result = subprocess.run([sys.executable, codegen_script, gen_dir], capture_output=True, text=True)

    if result.returncode != 0:
        raise AssertionError(f"Codegen failed: {result.stderr}")

    # define the autogenerated module names we want to import
    module_names = ["cc_energy", "t1_residual", "t2_residual", "t3_residual"]
    loaded_modules = {}

    # import each pq-generated file
    for name in module_names:
        if name in sys.modules:
            importlib.reload(sys.modules[name])
        loaded_modules[name] = importlib.import_module(name)

    # pass pq-generated functions into the ccsd solver
    mol, wfn = setup_psi4_test()
    mycc = cc(
        wfn, 
        mol, 
        nfzc=1, 
        cc_energy_func=loaded_modules["cc_energy"].cc_energy,
        t1_residual_func=loaded_modules["t1_residual"].t1_residual,
        t2_residual_func=loaded_modules["t2_residual"].t2_residual,
        t3_residual_func=loaded_modules["t3_residual"].t3_residual
    )

    en = mycc.t_solver()

    # check ccsd energy against psi4
    #assert np.isclose(en, -75.019819521964, rtol=1e-8, atol=1e-8)
    assert np.isclose(en, -75.019746392571, rtol=1e-8, atol=1e-8)

def test_ccsd_codegen():

    # pq codegen 
    codegen_script = os.path.join(script_path, "test_cases/ccsd_codegen.py")
    result = subprocess.run([sys.executable, codegen_script, gen_dir], capture_output=True, text=True)

    if result.returncode != 0:
        raise AssertionError(f"Codegen failed: {result.stderr}")

    # define the autogenerated module names we want to import
    module_names = ["cc_energy", "t1_residual", "t2_residual"]
    loaded_modules = {}

    # import each pq-generated file
    for name in module_names:
        if name in sys.modules:
            importlib.reload(sys.modules[name])
        loaded_modules[name] = importlib.import_module(name)

    # pass pq-generated functions into the ccsd solver
    mol, wfn = setup_psi4_test()
    mycc = cc(
        wfn, 
        mol, 
        nfzc=1, 
        cc_energy_func=loaded_modules["cc_energy"].cc_energy,
        t1_residual_func=loaded_modules["t1_residual"].t1_residual,
        t2_residual_func=loaded_modules["t2_residual"].t2_residual
    )

    en = mycc.t_solver()

    # check ccsd energy against psi4
    #assert np.isclose(en, -75.019715133639338, rtol=1e-8, atol=1e-8)
    assert np.isclose(en, -75.019641774768, rtol=1e-8, atol=1e-8)

def test_eomccsd_codegen():

    # pq codegen 
    codegen_script = os.path.join(script_path, "test_cases/eomccsd_codegen.py")
    result = subprocess.run([sys.executable, codegen_script, gen_dir], capture_output=True, text=True)

    if result.returncode != 0:
        raise AssertionError(f"Codegen failed: {result.stderr}")

    # define the autogenerated module names we want to import
    module_names = ["cc_energy", 
        "t1_residual", 
        "t2_residual",
        "right_sigma0",
        "right_sigma1",
        "right_sigma2"
    ]
    loaded_modules = {}

    # import each pq-generated file
    for name in module_names:
        if name in sys.modules:
            importlib.reload(sys.modules[name])
        loaded_modules[name] = importlib.import_module(name)

    # pass pq-generated functions into the ccsd solver
    mol, wfn = setup_psi4_test()
    mycc = cc(
        wfn, 
        mol, 
        nfzc=1, 
        cc_energy_func=loaded_modules["cc_energy"].cc_energy,
        t1_residual_func=loaded_modules["t1_residual"].t1_residual,
        t2_residual_func=loaded_modules["t2_residual"].t2_residual
    )

    en = mycc.t_solver()

    # check ccsd energy against psi4
    #assert np.isclose(en, -75.019715133639338, rtol=1e-8, atol=1e-8)
    assert np.isclose(en, -75.019641774768, rtol=1e-8, atol=1e-8)

    eomcc = eom_ccsd(mycc, 
        right_sigma0_func=loaded_modules["right_sigma0"].right_sigma0,
        right_sigma1_func=loaded_modules["right_sigma1"].right_sigma1,
        right_sigma2_func=loaded_modules["right_sigma2"].right_sigma2
     )

    ref_energies = [0.000000000000,
        0.356359777102,
        0.412605450358,
        0.457799399030,
        0.457998414869,
    ]

    eomcc.right_solver()

    assert np.allclose(ref_energies, eomcc.eom_cc_energy, rtol=1e-8, atol=1e-8)

    #eomcc.left_solver()

def main():
    #test_ccsd_spin_orbital_codegen()
    #test_ccsd_codegen()
    #test_ccsdt_codegen()
    #test_eomccsd_codegen()
    raise Exception("run with pytest")


if __name__ == "__main__":
    main()

