import pytest
import os
import contextlib

# Initialize log file
LOG_FILE = "pq_test.log"
@pytest.fixture(scope="session", autouse=True)
def initialize_log_file():
    with open(LOG_FILE, "w") as f:
        f.write("============================================================\n")
        f.write("    AUTOGENERATED CODE GENERATION AND EXECUTION TEST LOG    \n")
        f.write("============================================================\n\n")
    yield  

import numpy as np
import psi4    

from pdaggerq.numerical_utils.cc import cc
from pdaggerq.numerical_utils.eom_cc import eom_ccsd

def setup_psi4_test():

    # set up job for psi4
    mol = psi4.geometry("""
    0 1
    #O
    #H 1 1.0
    #H 1 1.0 2 104.5
    O            0.000000000000     0.000000000000    -0.068516219320 
    H            0.000000000000    -0.790689573744     0.543701060715 
    H            0.000000000000     0.790689573744     0.543701060715 
    #H            0.000000000000     0.000000000000     0.000000000000 
    #F            0.000000000000     0.000000000000     1.6
    no_reorient
    nocom
    symmetry c1
    """)

    # set options
    psi4.set_options({'basis': 'sto-3g',
                      'scf_type': 'pk',
                      'reference': 'uhf',
                      'r_convergence': 1e-12,
                      'e_convergence': 1e-12,
                      'd_convergence': 1e-12})

    # compute the Hartree-Fock energy and wave function
    scf_e, wfn = psi4.energy('SCF', return_wfn=True)

    return mol, wfn

@pytest.mark.ccsd_disk
def test_ccsd_codegen_disk():

    import os
    import subprocess
    import sys
    import importlib
    
    # Setup paths
    script_path = os.path.dirname(os.path.realpath(__file__))
    gen_dir = os.path.join(script_path, "generated_equations")
    os.makedirs(gen_dir, exist_ok=True)
    
    # Add the generation directory to sys.path so Python can import from it
    if gen_dir not in sys.path:
        sys.path.insert(0, gen_dir)

    with open(LOG_FILE, "a") as f:
        f.write(">>> Running CCSD (functions on disk) ...\n")    

        with contextlib.redirect_stdout(f):

            # Import pq codegen functions 
            from pdaggerq.numerical_utils.autogen import cc_residual

            cc_residual('cc_energy', ['t1', 't2'], [['1']], 'cc_energy', write_function = True)
            cc_residual('r1', ['t1', 't2'], [['e1(i,a)']], 't1_residual', write_function = True)
            cc_residual('r2', ['t1', 't2'], [['e2(i,j,b,a)']], 't2_residual', write_function = True)

            # define the autogenerated module names we want to import
            module_names = ["cc_energy", "t1_residual", "t2_residual"]
            local_namespace = {}

            # import each pq-generated file
            for name in module_names:
                if name in sys.modules:
                    importlib.reload(sys.modules[name])
                local_namespace[name] = importlib.import_module(name)

            # Pass pq-generated functions into the cc solver
            mol, wfn = setup_psi4_test()
            mycc = cc(
                wfn,
                mol,
                nfzc=1,
                cc_energy_func=local_namespace["cc_energy"].cc_energy,
                t1_residual_func=local_namespace["t1_residual"].t1_residual,
                t2_residual_func=local_namespace["t2_residual"].t2_residual,
            )

            en = mycc.t_solver()

            assert np.isclose(en, -75.019641774768, rtol=1e-10, atol=1e-10)

        f.write(">>> TEST PASSED: CCSD (functions on disk)\n")    

@pytest.mark.qed_ccsd
def test_qed_ccsd_codegen():

    with open(LOG_FILE, "a") as f:
        f.write(">>> Running QED-CCSD-21 ...\n")

        with contextlib.redirect_stdout(f):

            # Import pq codegen functions 
            from pdaggerq.numerical_utils.autogen import cc_residual

            # Create an empty dictionary to hold the pq-generated equations
            local_namespace = {}

            # Execute the code string in memory
            exec(cc_residual('cc_energy', ['t1', 't2', 't0,1', 't1,1', 't2,1'], [['1']], 'cc_energy', is_qed = True), globals(), local_namespace)
            exec(cc_residual('r1', ['t1', 't2', 't0,1', 't1,1', 't2,1'], [['e1(i,a)']], 't1_residual', is_qed = True), globals(), local_namespace)
            exec(cc_residual('r2', ['t1', 't2', 't0,1', 't1,1', 't2,1'], [['e2(i,j,b,a)']], 't2_residual', is_qed = True), globals(), local_namespace)
            exec(cc_residual('r0', ['t1', 't2', 't0,1', 't1,1', 't2,1'], [['B-']], 't0_1p_residual', is_qed = True), globals(), local_namespace)
            exec(cc_residual('r1', ['t1', 't2', 't0,1', 't1,1', 't2,1'], [['B-', 'e1(i,a)']], 't1_1p_residual', is_qed = True), globals(), local_namespace)
            exec(cc_residual('r2', ['t1', 't2', 't0,1', 't1,1', 't2,1'], [['B-', 'e2(i,j,b,a)']], 't2_1p_residual', is_qed = True), globals(), local_namespace)

            # Pass pq-generated functions into the cc solver
            mol, wfn = setup_psi4_test()
            mycc = cc(
                wfn,
                mol,
                nfzc=0,
                cc_energy_func=local_namespace["cc_energy"],
                t1_residual_func=local_namespace["t1_residual"],
                t2_residual_func=local_namespace["t2_residual"],
                t0_1p_residual_func=local_namespace["t0_1p_residual"],
                t1_1p_residual_func=local_namespace["t1_1p_residual"],
                t2_1p_residual_func=local_namespace["t2_1p_residual"],
                cavity_lambda=[0.0, 0.0, 0.05],
                cavity_frequency=0.07349864501573 # 2eV
            )

            en = mycc.t_solver()

            assert np.isclose(en, -75.015650410563, rtol=1e-10, atol=1e-10)

        f.write(">>> TEST PASSED: QED-CCSD-21\n")

@pytest.mark.ccsd
def test_ccsd_codegen():

    with open(LOG_FILE, "a") as f:
        f.write(">>> Running CCSD ...\n")

        with contextlib.redirect_stdout(f):

            # Import pq codegen functions 
            from pdaggerq.numerical_utils.autogen import cc_residual

            # Create an empty dictionary to hold the pq-generated equations
            local_namespace = {}
            
            # Execute the code string in memory
            exec(cc_residual('cc_energy', ['t1', 't2'], [['1']], 'cc_energy'), globals(), local_namespace)
            exec(cc_residual('r1', ['t1', 't2'], [['e1(i,a)']], 't1_residual'), globals(), local_namespace)
            exec(cc_residual('r2', ['t1', 't2'], [['e2(i,j,b,a)']], 't2_residual'), globals(), local_namespace)
            
            # Pass pq-generated functions into the cc solver
            mol, wfn = setup_psi4_test()
            mycc = cc(
                wfn, 
                mol, 
                nfzc=1, 
                cc_energy_func=local_namespace["cc_energy"],
                t1_residual_func=local_namespace["t1_residual"],
                t2_residual_func=local_namespace["t2_residual"]
            )

            en = mycc.t_solver()

            assert np.isclose(en, -75.019641774768, rtol=1e-10, atol=1e-10)

        f.write(">>> TEST PASSED: CCSD\n")    

@pytest.mark.ucc3
def test_uccsd_3_codegen():

    with open(LOG_FILE, "a") as f:
        f.write(">>> Running UCCSD(3) ...\n")

        with contextlib.redirect_stdout(f):

            # Import pq codegen functions 
            from pdaggerq.numerical_utils.autogen import uccsd_energy
            from pdaggerq.numerical_utils.autogen import uccsd_singles_residual
            from pdaggerq.numerical_utils.autogen import uccsd_doubles_residual

            # Create an empty dictionary to hold the pq-generated equations
            local_namespace = {}
            
            # Execute the code string in memory
            exec(uccsd_energy(3, 'cc_energy', 'cc_energy'), globals(), local_namespace)
            exec(uccsd_singles_residual(2, 'r1', [['e1(i,a)']], 't1_residual'), globals(), local_namespace)
            exec(uccsd_doubles_residual(2, 'r2', [['e2(i,j,b,a)']], 't2_residual'), globals(), local_namespace)

            # Pass pq-generated functions into the cc solver
            mol, wfn = setup_psi4_test()
            mycc = cc(
                wfn, 
                mol, 
                nfzc=1, 
                cc_energy_func=local_namespace["cc_energy"], 
                t1_residual_func=local_namespace["t1_residual"],
                t2_residual_func=local_namespace["t2_residual"]
            )

            en = mycc.t_solver()

            assert np.isclose(en, -75.020242934640, rtol=1e-10, atol=1e-10)

        f.write(">>> TEST PASSED: UCCSD(3)\n")    

@pytest.mark.ucc4
def test_uccsd_4_codegen():

    with open(LOG_FILE, "a") as f:
        f.write(">>> Running UCCSD(4) ...\n")

        with contextlib.redirect_stdout(f):

            # Import pq codegen functions 
            from pdaggerq.numerical_utils.autogen import uccsd_energy
            from pdaggerq.numerical_utils.autogen import uccsd_singles_residual
            from pdaggerq.numerical_utils.autogen import uccsd_doubles_residual

            # Create an empty dictionary to hold the pq-generated equations
            local_namespace = {}

            # Execute the code string in memory
            exec(uccsd_energy(4, 'cc_energy', 'cc_energy'), globals(), local_namespace)
            exec(uccsd_singles_residual(3, 'r1', [['e1(i,a)']], 't1_residual'), globals(), local_namespace)
            exec(uccsd_doubles_residual(3, 'r2', [['e2(i,j,b,a)']], 't2_residual'), globals(), local_namespace)

            # Pass pq-generated functions into the cc solver
            mol, wfn = setup_psi4_test()
            mycc = cc(
                wfn,
                mol,
                nfzc=1,
                cc_energy_func=local_namespace["cc_energy"], 
                t1_residual_func=local_namespace["t1_residual"],
                t2_residual_func=local_namespace["t2_residual"]
            )

            en = mycc.t_solver()

            assert np.isclose(en, -75.019695059108, rtol=1e-10, atol=1e-10)

        f.write(">>> TEST PASSED: UCCSD(4)\n")    

@pytest.mark.lambda_ccsd
def test_lambda_ccsd_codegen():

    with open(LOG_FILE, "a") as f:
        f.write(">>> Running lambda-CCSD ...\n")

        with contextlib.redirect_stdout(f):
        
            # Import pq codegen functions 
            from pdaggerq.numerical_utils.autogen import cc_residual
            from pdaggerq.numerical_utils.autogen import lambda_cc_residual
            from pdaggerq.numerical_utils.autogen import lambda_cc_pseudoenergy
                
            # Create an empty dictionary to hold the pq-generated equations
            local_namespace = {}
   
            # Execute the code string in memory
            exec(cc_residual('cc_energy', ['t1', 't2'], [['1']], 'cc_energy'), globals(), local_namespace)
            exec(cc_residual('r1', ['t1', 't2'], [['e1(i,a)']], 't1_residual'), globals(), local_namespace)
            exec(cc_residual('r2', ['t1', 't2'], [['e2(i,j,b,a)']], 't2_residual'), globals(), local_namespace)

            exec(lambda_cc_pseudoenergy('cc_pseudoenergy', [['l1'], ['l2']], [['1']], 'cc_pseudoenergy'), globals(), local_namespace)
            exec(lambda_cc_residual('r1', ['t1', 't2'], [['l1'], ['l2']], 'e1(a,i)', 'l1_residual'), globals(), local_namespace)
            exec(lambda_cc_residual('r2', ['t1', 't2'], [['l1'], ['l2']], 'e2(a,b,j,i)', 'l2_residual'), globals(), local_namespace)

            # Pass pq-generated functions into the cc solver
            mol, wfn = setup_psi4_test()

            mycc = cc(
                wfn, 
                mol,
                nfzc=1,
                cc_energy_func=local_namespace["cc_energy"],
                t1_residual_func=local_namespace["t1_residual"],
                t2_residual_func=local_namespace["t2_residual"],
                cc_pseudoenergy_func=local_namespace["cc_pseudoenergy"],
                l1_residual_func=local_namespace["l1_residual"],
                l2_residual_func=local_namespace["l2_residual"],
            )
            
            en = mycc.t_solver()

            assert np.isclose(en, -75.019641774768, rtol=1e-10, atol=1e-10)

            pseudoen = mycc.lambda_solver()

            assert np.isclose(pseudoen, -0.054046897553, rtol=1e-10, atol=1e-10)

        f.write(">>> TEST PASSED: lambda-CCSD\n")    

@pytest.mark.ccsdt
def test_ccsdt_codegen():

    with open(LOG_FILE, "a") as f:
        f.write(">>> Running CCSDT ...\n")

        with contextlib.redirect_stdout(f):

            # Import pq codegen functions 
            from pdaggerq.numerical_utils.autogen import cc_residual

            # Create an empty dictionary to hold the pq-generated equations
            local_namespace = {}
            
            # Execute the code string in memory
            exec(cc_residual('cc_energy', ['t1', 't2', 't3'], [['1']], 'cc_energy'), globals(), local_namespace)
            exec(cc_residual('r1', ['t1', 't2', 't3'], [['e1(i,a)']], 't1_residual'), globals(), local_namespace)
            exec(cc_residual('r2', ['t1', 't2', 't3'], [['e2(i,j,b,a)']], 't2_residual'), globals(), local_namespace)
            exec(cc_residual('r3', ['t1', 't2', 't3'], [['e3(i,j,k,c,b,a)']], 't3_residual'), globals(), local_namespace)
            
            # Pass pq-generated functions into the cc solver
            mol, wfn = setup_psi4_test()
            mycc = cc(
                wfn,
                mol, 
                nfzc=1,  
                cc_energy_func=local_namespace["cc_energy"],
                t1_residual_func=local_namespace["t1_residual"],
                t2_residual_func=local_namespace["t2_residual"],
                t3_residual_func=local_namespace["t3_residual"]
            )

            en = mycc.t_solver()

            assert np.isclose(en, -75.019746392571, rtol=1e-10, atol=1e-10)

        f.write(">>> TEST PASSED: CCSDT\n")    

@pytest.mark.cc3
def test_cc3_codegen():

    with open(LOG_FILE, "a") as f:
        f.write(">>> Running CC3 ...\n")

        with contextlib.redirect_stdout(f):

            # Import pq codegen functions 
            from pdaggerq.numerical_utils.autogen import cc_residual
            from pdaggerq.numerical_utils.autogen import cc3_triples_residual

            # Create an empty dictionary to hold the pq-generated equations
            local_namespace = {}

            # Execute the code string in memory
            exec(cc_residual('cc_energy', ['t1', 't2', 't3'], [['1']], 'cc_energy'), globals(), local_namespace)
            exec(cc_residual('r1', ['t1', 't2', 't3'], [['e1(i,a)']], 't1_residual'), globals(), local_namespace)
            exec(cc_residual('r2', ['t1', 't2', 't3'], [['e2(i,j,b,a)']], 't2_residual'), globals(), local_namespace)
            exec(cc3_triples_residual('r3', [['e3(i,j,k,c,b,a)']], 't3_residual'), globals(), local_namespace)
            
            # Pass pq-generated functions into the cc solver
            mol, wfn = setup_psi4_test()
            mycc = cc(
                wfn,
                mol, 
                nfzc=1,  
                cc_energy_func=local_namespace["cc_energy"],
                t1_residual_func=local_namespace["t1_residual"],
                t2_residual_func=local_namespace["t2_residual"],
                t3_residual_func=local_namespace["t3_residual"]
            )

            en = mycc.t_solver()

            assert np.isclose(en, -75.019717612241, rtol=1e-10, atol=1e-10)

        f.write(">>> TEST PASSED: CC3\n")    

@pytest.mark.eomcc
def test_eomccsd_codegen():

    with open(LOG_FILE, "a") as f:
        f.write(">>> Running EOMCCSD ...\n")

        with contextlib.redirect_stdout(f):

            # Import pq codegen functions 
            from pdaggerq.numerical_utils.autogen import cc_residual
            from pdaggerq.numerical_utils.autogen import eomcc_sigma

            # Create an empty dictionary to hold the pq-generated equations
            local_namespace = {}

            # Execute the code string in memory
            exec(cc_residual('cc_energy', ['t1', 't2'], [['1']], 'cc_energy'), globals(), local_namespace)
            exec(cc_residual('r1', ['t1', 't2'], [['e1(i,a)']], 't1_residual'), globals(), local_namespace)
            exec(cc_residual('r2', ['t1', 't2'], [['e2(i,j,b,a)']], 't2_residual'), globals(), local_namespace)

            exec(eomcc_sigma('sigma0', ['t1', 't2'], [['1']], [['r0'], ['r1'], ['r2']], 'right_sigma0'), globals(), local_namespace)
            exec(eomcc_sigma('sigma1', ['t1', 't2'], [['e1(i,a)']], [['r0'], ['r1'], ['r2']], 'right_sigma1'), globals(), local_namespace)
            exec(eomcc_sigma('sigma2', ['t1', 't2'], [['e2(i,j,b,a)']], [['r0'], ['r1'], ['r2']], 'right_sigma2'), globals(), local_namespace)

            exec(eomcc_sigma('sigma0', ['t1', 't2'], [['l0'], ['l1'], ['l2']], [['1']], 'left_sigma0'), globals(), local_namespace)
            exec(eomcc_sigma('sigma1', ['t1', 't2'], [['l0'], ['l1'], ['l2']], [['e1(a,i)']], 'left_sigma1'), globals(), local_namespace)
            exec(eomcc_sigma('sigma2', ['t1', 't2'], [['l0'], ['l1'], ['l2']], [['e2(a,b,j,i)']], 'left_sigma2'), globals(), local_namespace)

            # Pass pq-generated functions into the cc solver
            mol, wfn = setup_psi4_test()
            mycc = cc(
                wfn, 
                mol, 
                nfzc=1, 
                cc_energy_func=local_namespace["cc_energy"],
                t1_residual_func=local_namespace["t1_residual"],
                t2_residual_func=local_namespace["t2_residual"]
            )

            en = mycc.t_solver()

            assert np.isclose(en, -75.019641774768, rtol=1e-10, atol=1e-10)

            eomcc = eom_ccsd(mycc, 
                right_sigma0_func=local_namespace["right_sigma0"],
                right_sigma1_func=local_namespace["right_sigma1"],
                right_sigma2_func=local_namespace["right_sigma2"],
                left_sigma0_func=local_namespace["left_sigma0"],
                left_sigma1_func=local_namespace["left_sigma1"],
                left_sigma2_func=local_namespace["left_sigma2"]
             )

            ref_energies = [0.000000000000,
                0.356359777102,
                0.412605450358,
                0.457799399030,
                0.457998414869,
            ]

            eomcc.right_solver()

            assert np.allclose(ref_energies, eomcc.eom_cc_energy, rtol=1e-10, atol=1e-10)

            eomcc.left_solver()

            assert np.allclose(ref_energies, eomcc.eom_cc_energy, rtol=1e-10, atol=1e-10)

        f.write(">>> TEST PASSED: EOMCCSD\n")    

def main():
    #test_ccsd_codegen_disk()
    #test_ccsd_codegen()
    test_qed_ccsd_codegen()
    #test_ccsdt_codegen()
    #test_cc3_codegen()
    #test_eomccsd_codegen()
    #test_lambda_ccsd_codegen()
    #test_uccsd_3_codegen()
    #test_uccsd_4_codegen()
    #raise Exception("run with pytest")

if __name__ == "__main__":
    main()

