# pytest.ini
[pytest]
markers =
    ccsd: numerical CCSD test
    ccsd_disk: numerical CCSD test with python functions written to disk
    ccsdt: numerical CCSDT test
    cc3: numerical CC3 test
    lambda_ccsd: numerical lambda-CCSD test
    qed_ccsd: numerical QED-CCSD-21
    eomcc: numerical EOMCCSD test with right/left eigensolve
    ucc3: numerical UCCSD(3) test
    ucc4: numerical UCCSD(4) test
