#!/bin/bash

tests=(cc3 ccsd_codegen ccsd_d1 ccsd_d2 ccsd_doubles ccsd_energy ccsd ccsd_singles ccsd_t ccsdt cid_d1 cid_d2 cisd_hamiltonian ea_eom_ccsd ea_eom_ccsdt eom_ccsd_d1_by_hand eom_ccsd_d1 eom_ccsd_hamiltonian eom_ccsd eom_ccsd_sigma extended_rpa ip_eom_ccsd ip_eom_ccsdt lambda_doubles_codegen lambda_doubles lambda_singles_codegen lambda_singles rdm_mappings)

quick_tests=(cc3 ccsd eom_ccsd_sigma)

for i in ${!tests[@]};
do
    my_test=${tests[$i]}
    echo ${my_test}
    python ${my_test}.py > ${my_test}.out
    diff reference_outputs/${my_test}.ref ${my_test}.out
done

